#!/bin/python3

# Karahanlı sadakatini takdir ediyor.

import argparse
import requests
from requests_ntlm import HttpNtlmAuth
import urllib3
from datetime import datetime

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

MENU_URL = ''
AUTH_URL = ''
DOMAIN = ""
USERNAME = ""
PASSWORD = ""
KAMPUS = ""


def printer(data):
    data = data.get("YemekListesi")
    for i in data:
        print(i, end="\n")


def filter_menu(menu, menu_type):
    for data in menu:
        if (data.get("Lokasyon") == KAMPUS and data.get("YemekMenusuTuru") == menu_type):
            printer(data)


def getMenu(auth):
    bearer_token = auth.get("Data").get("Token")
    headers = {
        'Authorization': f'Bearer {bearer_token}',
    }
    current_date = datetime.now()
    formatted_date = current_date.strftime("%d-%m-%Y")

    data = {
        "tarih": formatted_date
    }
    response = requests.post(MENU_URL, headers=headers, json=data, verify=False)
    if response.status_code == 200:
        return response.json()


def login():
    username_domain = f'{DOMAIN}\\{USERNAME}'

    # Send a GET request with NTLM authentication
    response = requests.get(AUTH_URL, auth=HttpNtlmAuth(username_domain, PASSWORD), verify=False)
    if response.status_code == 200:
        return response.json()


def main():
    parser = argparse.ArgumentParser(description="Tubitak günün yemek menüsü cli uygulaması")
    subparsers = parser.add_subparsers(dest="command", help="Subcommands")

    subparsers.add_parser("ogle", help="Öğlen menü için")
    subparsers.add_parser("aksam", help="Akşam menü")
    subparsers.add_parser("salata", help="Salatabar menü için")
    subparsers.add_parser("diyet", help="Diyet menü için")
    subparsers.add_parser("vej", help="Vegan menü için")
    args = parser.parse_args()

    auth = login()
    menu = getMenu(auth)

    if args.command == "aksam":
        filter_menu(menu, 2)
    elif args.command == "ogle":
        filter_menu(menu, 1)
    elif args.command == "salata":
        filter_menu(menu, 5)
    elif args.command == "diyet":
        filter_menu(menu, 3)
    elif args.command == "vej":
        filter_menu(menu, 6)
    elif args.command is None:
        filter_menu(menu, 1)  # Default to Öğlen menu


if __name__ == "__main__":
    main()
